spring.application.name=iron-empire-backend

# Configuración de la bd.
# ${VARIABLE:defecto} --> Si existe, inyectá su valor, si no, usá el valor que está después de los dos puntos.
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:iron_empire_bd}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:contra}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate / JPA.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


admin.general.nombre=${ADMIN_NOMBRE:Admin}
admin.general.apellido=${ADMIN_APELLIDO:General}
admin.general.dni=${ADMIN_DNI:00000000}
admin.general.email=${ADMIN_EMAIL:admin@ironempire.com}
admin.general.telefono=${ADMIN_TELEFONO:0000000000}
admin.general.contrasenia=${ADMIN_CONTRASENIA:admin123}
